from telethon import TelegramClient, sync, events
from telethon.tl.functions.messages import GetHistoryRequest, GetBotCallbackAnswerRequest
from telethon.tl.functions.channels import JoinChannelRequest
from telethon.errors import SessionPasswordNeededError
from telethon.errors import FloodWaitError
from time import sleep, time
from colorama import Fore,Style, init as color_ama
color_ama(autoreset=True)
import json, re, sys, os, random

banner = Style.BRIGHT+Fore.YELLOW +  """

   ____               _   
  / ___| ___ __ _ ___| |_ 
 | |  _ / __/ _` / __| __|
 | |_| | (_| (_| \__ \ |_ 
  \____|\___\__,_|___/\__|
                          """

putih = Style.BRIGHT+Fore.WHITE
hijau = Style.BRIGHT+Fore.GREEN
merah = Style.BRIGHT+Fore.RED
kuning = Style.BRIGHT+Fore.YELLOW
reset = Fore.RESET
biru = Style.BRIGHT+Fore.BLUE


os.system('clear') 
print(banner)
print("\n")
print(f'{hijau}[+] Indonesia/English')
import random
import sys
import time
def mengetik(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
#kecepatan mengetik
        time.sleep(random.random() * 0.2)
#ubah angka 0.1 sesuai keinginan kamu
#angka terkecil adalah yang paling cepat
#angka terbesar adalah yang paling lambat
mengetik("[+] Ini Adalah Program Ilegal\n[+] Semua Resiko Harap Ditanggung Pengguna..!!\n[+] This Is An Illegal Program\n[+] All Risks Borne by Users...!\n")
if not os.path.exists('session'):
    os.makedirs('session')
if len(sys.argv) < 2:
    print( Fore.RED + '\n\nUsage : python main.py +62' + Fore.RESET)
    sys.exit(1)
api_id = 29826983
api_hash = '8de0ed7bbdc2d04c1938226d6bb9af38'
phone_number = sys.argv[1]
client = TelegramClient('session/' + phone_number, api_id, api_hash)
client.connect()
if not client.is_user_authorized():
    try:
        client.send_code_request(phone_number)
        me = client.sign_in(phone_number, input(Fore.WHITE + 'Enter Yout Code Code : '))
    except SessionPasswordNeededError:
        passw = input(Fore.RESET + 'Your 2fa Password : ')
        me = client.start(phone_number, passw)
saia = client.get_me()
print('[*]Account:',saia.first_name)
print('[*]Phone:',saia.phone,'\n')
channel_username = '@gcstbosss'
channel_entity = client.get_entity('@gcstbosss')
print('Memulai Bot Gcast..!')


while True:
  try:
    client.send_message(entity=channel_entity, message='.gcast zayaa lagi o,p,e,nn ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast sini la sm zayaa ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast c,h ,p,ribnya ka ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast Oopnnnnnn ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast Opnvci ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast Call dm yu ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast Hai kak ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast Ayo ay pcs🥺 ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast morn horny:( ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast Yug sayang di order ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast gomeennn ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast open ka ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast terzayaa zayaa ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast awikwok bgt luwh ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast apalaa ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast mff yh ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast o,pen b,ngt ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast pc ay ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast akuh zayang kamu jg zayang ahahaahha ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast cpcpccp ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast info ah ah ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast aht aht ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast ddii,i ,biii,oo ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast yang pasti" ajh ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast gimana mau maju orng hobi nya mundur trus ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast Yakin gamau tmnnin disini ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast knp ak beban bgt ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast bii bantuinn ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast biiiii ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast ayy ahhahh ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast sn,ge bgt ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast sinii aa ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast biar apaaa biarin hehe ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast sayang ma aku?? ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast sangee bgt woy ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast Vcsss ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast kepengenn ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast tmnin ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast ay sni ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast b,io ay ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast aht aht ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast om,ek d,ii b,ioo ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast basah bgt ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast disekolah gimanaa ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast snge ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast hii bangg ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast kitaa aht" brg ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast t,mennn inn zayaaa ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast ayaaanggg ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.gcast siniiiilaaaaa ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : ruz')
    sleep(5)
    
    
  except:
    print(f'{hijau} Gcast gagal.! {putih} gcast by : ruz')
    sleep(120)

sys.exit()
client.disconnect()
