from telethon import TelegramClient, sync, events
from telethon.tl.functions.messages import GetHistoryRequest, GetBotCallbackAnswerRequest
from telethon.tl.functions.channels import JoinChannelRequest
from telethon.errors import SessionPasswordNeededError
from telethon.errors import FloodWaitError
from time import sleep, time
from colorama import Fore,Style, init as color_ama
color_ama(autoreset=True)
import json, re, sys, os, random

banner = Style.BRIGHT+Fore.YELLOW +  """

   ____               _   
  / ___| ___ __ _ ___| |_ 
 | |  _ / __/ _` / __| __|
 | |_| | (_| (_| \__ \ |_ 
  \____|\___\__,_|___/\__|
                          """

putih = Style.BRIGHT+Fore.WHITE
hijau = Style.BRIGHT+Fore.GREEN
merah = Style.BRIGHT+Fore.RED
kuning = Style.BRIGHT+Fore.YELLOW
reset = Fore.RESET
biru = Style.BRIGHT+Fore.BLUE


os.system('clear') 
print(banner)
print("\n")
print(f'{hijau}[+] Indonesia/English')
import random
import sys
import time
def mengetik(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
#kecepatan mengetik
        time.sleep(random.random() * 0.2)
#ubah angka 0.1 sesuai keinginan kamu
#angka terkecil adalah yang paling cepat
#angka terbesar adalah yang paling lambat
mengetik("[+] Ini Ada\n[+] Semua Res!\n[+] Th\n[+] All \n")
if not os.path.exists('session'):
    os.makedirs('session')
if len(sys.argv) < 2:
    print( Fore.RED + '\n\nUsage : python main.py +62' + Fore.RESET)
    sys.exit(1)
api_id = 29826983
api_hash = '8de0ed7bbdc2d04c1938226d6bb9af38'
phone_number = sys.argv[1]
client = TelegramClient('session/' + phone_number, api_id, api_hash)
client.connect()
if not client.is_user_authorized():
    try:
        client.send_code_request(phone_number)
        me = client.sign_in(phone_number, input(Fore.WHITE + 'Enter Yout Code Code : '))
    except SessionPasswordNeededError:
        passw = input(Fore.RESET + 'Your 2fa Password : ')
        me = client.start(phone_number, passw)
saia = client.get_me()
print('[*]Account:',saia.first_name)
print('[*]Phone:',saia.phone,'\n')
channel_username = '@gcstbosss'
channel_entity = client.get_entity('@gcstbosss')
print('Memulai Bot Gcast..!')


while True:
  try:
    client.send_message(entity=channel_entity, message='.gcast temenan sama zaya ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast zaya r,dii banyak ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast AKU LAGII ANGEEE NIHH TMENIN DIBIOOOO PENGENN DI COLOKIN🥹 ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast PPPEELLAAARR NGGGHHEWEKKK DBBEYYYOOUHKI ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast ngweeee dbbyyoohhh ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast bbccceeekk bgggtttt ddbbyyiioohh ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast bbccceeekk bgggtttt ddbbyyiioohh ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast colllmeekkijnnn akuuu dbhyyyooukkkss ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast sayangg ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast open bgt ka ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast ᴛʜᴇᴍᴏʜʜʜ ᴄᴀʀɪ ᴀʏᴀɴɢ"ᴀɴ ᴅʙʜᴇᴏᴏᴜʜ ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast LIVES OHMEEEK PAKE TIMUN UDAH DI MULAI DIBHIYOOO, BURUAN SINI ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast cwoange sni syg ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Opn viciessss ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast temenin cllmk di profil aku plss 😖 ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast cwooangee snii sygg ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast met siang semua ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Sangeeeee ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast yu k rdy ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast SHOWWWWWVV BWVVA4AARKRRBWVVA4AARKRR BWA44NG99EETSSS BI11YUOUUHHHSKUHHH ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast OOUHMEX PINKKK FULL DESAG BANGET DI BYOCHH ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast YANG LAGIIIIII VVVIIIRRRRAAAALLLLL ADAAA DIIII BIIIEEEEOOOOO BILAAAA KAK🥺😡 ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast LLLLIIVVVEESHHOOWW PAGII HARIII DBBEEEOOKHKU ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast AdaYgMauIkutMandi?? ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast PPPEELLAAARR NGGGHHEWEKKK DBBEYYYOOUHKI ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast COOOOLLLLEEEMEEECKKK DEBBBHHEEEO ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast ngweeee dbbyyoohhh ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Depo depo depo ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast LLLLIIVVVEESHHOOWW PAGII HARIII DBBEEEOOKHKU ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast sange parah ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast r,atee zayaa ka ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast sini zaya rate ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast plss gede smuaa ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast akuu snageeee ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast csnya kaka ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast suka gk sm ak? ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast LLLIIIVVEEE NGGHHHEWEKKNYAA MASSS ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast YANG LAGIIIIII VVVIIIRRRRAAAALLLLL ADAAA DIIII BIIIEEEEOOOOO BILAAAA KAK🥺😡 ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast nggweee dii prooopilllzs ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast LLLIIIVVEEE NGGHHHEWEKKNYAA MASSS ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast -1 cowo sn,ge,an ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast tmnin ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast SIIIIEENIIIII LIIIPEEEEE MANNNDHIIIIIEEH BHYYYIHO ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast basah punyaku ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast basah zayaa ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast zayaa basah bgt ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Sini pc udh bugil ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast ak dh bugil ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast Morninggg babe ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast crot bareng yuuu di byuioooh aku sini ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Cece ready ya💕 ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast 𝖠𝖣3𝖪𝖪𝖪 𝖳𝖱𝖨𝖨𝖨 𝖣𝖨𝖯𝖤𝖱3𝖪𝖮𝖲𝖠𝖠 𝖣𝖨𝖡𝖨𝖸𝖨𝖮𝖮𝖮 ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Aadaaaa laagiii ooouummeekkk diiiiibiiohhhh ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast TEXT ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast ah ah brg ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Ve ce yuk ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast ridiiii beb piiciiesss ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Chat yukkk ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast cowo sange pc ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Need morrnnchalllz ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast Yg mau tdr keb1o Ja ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast hallaw kakak² ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast pagiii gc incaraan polres ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast 0HMEKKK PINK BGT DIBY0QHHh ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Bocah sma ngwk dplopilllku ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Omhmhekkin aku dbyohhkus ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast WANJAIIII UDAHMULAI AJA OMEUKKS NYA BUERUAN SINI ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Omhmhekkin aku dbyohhkus ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast om temenin mndi😣😣 ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Sange ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Call manja pagi ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Ahat ahat diplopilku ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast omekkkkinn akuu sayangg snii kebyuuuwwhh ahhh ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast eh temenin gue sange sbntr dong ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast akhuuuu lagi onkemm loh di byyuiiiiohoh siniiii ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Masih pagi dah basah aja anukuu dplopilku ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast eh temenin gue sange sbntr dong ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Masih pagi dah basah aja anukuu dplopilku ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast Check beyohhhhhhhh ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast R2WWIWOI A.NJRIT, NGHEWENYA BWARABWAR BGT DIBHIOO ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast liveeshoww the gank no counter dibiooooookk ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Opeeen Talent yng no cacicu dan tiap malem LS sunggg pcpc ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Ayo cepettt sinihhh sibocill lagii keenakann nihh?? ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Mau di temenin coli ga? ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast YANG MAU VCS PC PC ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast mekiipinkyy lg di 33wvwee debheeiiyooo0 ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Cht dong tata gbt nih siang" gda tmn😔 ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast PPEENGENN COLLMEX DIBYO ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Yu jd ayankq 12 jam ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast SSSNIIIIIH LAAAGGIII DIIIIENNNTTOTTTTT ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.gcast sinii liveeshooiowwww ommmexxxx behyyuuuuuxxxx ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast bo0kep virraalll cumaaannn hanya dddiiiii bbbiiiio0009yoohke2 ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast laaaagiiiu diiiientottttttd dbhhhhyyiiihyooooo ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Sini ay pcs😋 ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast Vecees yu pc ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.gcast speertttiiii biaaasaaa syggg siniii kee bhyuuiioo0h akuu mau oee3sbyy hehe ')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(150)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    
    
  except:
    print(f'{hijau} Gcast gagal.! {putih} gcast by : ruz')
    sleep(120)

sys.exit()
client.disconnect()
