from telethon import TelegramClient, sync, events
from telethon.tl.functions.messages import GetHistoryRequest, GetBotCallbackAnswerRequest
from telethon.tl.functions.channels import JoinChannelRequest
from telethon.errors import SessionPasswordNeededError
from telethon.errors import FloodWaitError
from time import sleep, time
from colorama import Fore,Style, init as color_ama
color_ama(autoreset=True)
import json, re, sys, os, random

banner = Style.BRIGHT+Fore.YELLOW +  """

   ____               _   
  / ___| ___ __ _ ___| |_ 
 | |  _ / __/ _` / __| __|
 | |_| | (_| (_| \__ \ |_ 
  \____|\___\__,_|___/\__|
                          
  Creator : MK iruz || Youtube : MK iruz
  Support : Cocentz404 || Youtube : Cocentz404"""

putih = Style.BRIGHT+Fore.WHITE
hijau = Style.BRIGHT+Fore.GREEN
merah = Style.BRIGHT+Fore.RED
kuning = Style.BRIGHT+Fore.YELLOW
reset = Fore.RESET
biru = Style.BRIGHT+Fore.BLUE


os.system('clear') 
print(banner)
print("\n")
print(f'{hijau}[+] Indonesia/English')
import random
import sys
import time
def mengetik(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
#kecepatan mengetik
        time.sleep(random.random() * 0.2)
#ubah angka 0.1 sesuai keinginan kamu
#angka terkecil adalah yang paling cepat
#angka terbesar adalah yang paling lambat
mengetik("[+] Ini Adalah Program Ilegal\n[+] Semua Resiko Harap Ditanggung Pengguna..!!\n[+] This Is An Illegal Program\n[+] All Risks Borne by Users...!\n")
if not os.path.exists('session'):
    os.makedirs('session')
if len(sys.argv) < 2:
    print( Fore.RED + '\n\nUsage : python main.py +62' + Fore.RESET)
    sys.exit(1)
api_id = 29826983
api_hash = '8de0ed7bbdc2d04c1938226d6bb9af38'
phone_number = sys.argv[1]
client = TelegramClient('session/' + phone_number, api_id, api_hash)
client.connect()
if not client.is_user_authorized():
    try:
        client.send_code_request(phone_number)
        me = client.sign_in(phone_number, input(Fore.WHITE + 'Enter Yout Code Code : '))
    except SessionPasswordNeededError:
        passw = input(Fore.RESET + 'Your 2fa Password : ')
        me = client.start(phone_number, passw)
saia = client.get_me()
print('[*]Account:',saia.first_name)
print('[*]Phone:',saia.phone,'\n')
channel_username = '@gcastod'
channel_entity = client.get_entity('@gcastod')
print('Memulai Bot Gcast..!')


while True:
  try:
    
    client.send_message(entity=channel_entity, message='.gcast 𝗟𝗜𝗜𝗜𝗣𝗣𝗘𝗘𝗘𝗦𝗛𝗢𝗢𝗪𝗪 𝗡𝗚𝗚𝗚𝗘𝗘𝗘𝗘𝗪𝗪𝗘𝗘𝗘 𝗗𝗜𝗕𝗜𝗜𝗜𝗢𝗢𝗢𝗛𝗛𝗛')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast BATLEEE  OMEKCKK VS BATLEEE COLY DI BIUHHHHHHH1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast UD4AHHHHHH D1MUULAIIIII BURU4NNNNNN CEKKKKKK B1000KKKKKKKCKKK1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast TIEEEEMMEEEININNN AKKKUUU SAINGGGEEEEKK DDDEEEBEEE11O')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast MEM31MMMLMKS TEMBEM DIIBYIIOOU AK SAYANGGGGF')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast LIVFEEE NNGEUWEEE UDAAHHH MULAIIII DI BIYO0OOOU BURU JOINNNN1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast TIEEEMMMMEEEININN AKKKUUU SAINGDGGE3EEEKK DDDEEEBEEEOI')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast SOKK1NN TM0 C`UANN DIBYIOUHHH1HH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast ANA4K `SMMA NGEU33 SAMA OM` DI BBHHEYOKKK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast SSSIIAAIAR.RAAA`N LANGSUNG PER0MEEEKAAANN DIB;1Y000HHHKKkk')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast LLI`STINIIIi.IERR KIAA OMEXKCG BAWBRBWRR DBYOHGHHHFF')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast OOOUH`HMEX PINKK.KK FULL DESAAG BANNGGEET DI BYOCHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast AQKU ANGG`HEE.KKKK PARAHHHHDI BYUIOHHHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast CCH``OLLL`ME.E3KKKKKKINNNN BBBBHHHIIIYYUUUUHHHUK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast `CCHHOL.LLL MEEEKKKKINNNN BHH`HYIIIIOUYHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast NHN-G.UEEWEEE BBRU`TALLL BGTTT DI BIYOOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast `CHOLLLLLMEEFEKKMK`INNNN BHIHHYIIIOUYHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast ``MMMA`4MMIIII OOE.MM`EEEXXCKK BBBHYIIIOOUKKIII')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast OO.OHHHHME.EECXK.KIN`NN MOMMMIIIIIKUI BHHHHIIIIOOOYOOOOK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast MMAAA4AMMIIII OOEM`MMEEEXXCKK BBBHYIIIOOUKKIIII')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast SSSIIAAIAJRAAAN LANG`ASUNG PER0MEEEKAAANN DIB;1Y000HHKKkk')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast CHEAAKK DI PLHJAOP`JIL AKU ADA YANHG LAGI ENHAK ENSHAK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast OOUHHMEX PIJNKA`KK FULL DESAAG BANNGGET DI BYOCHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast AKUUUOUU COOLLLME`AJEEKKK BHYYYEIOOOOIOOKK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast SIII AALEEAAA AANG`EEJEEE BBHYYYYYTOOOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(500)
    client.send_message(entity=channel_entity, message='.gcast SSIARAAAN LAANGISAU`NG PPER0MEEKAAANN DIB;1Y000HHKKkk')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(500)
    client.send_message(entity=channel_entity, message='.gcast CCEK DI PLIHOPJIL A`KU AAADA YAANG LAGI ENHAK ENHAK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(400)
    client.send_message(entity=channel_entity, message='.gcast NNNONTON 0VMEJECKAK`K YUKKKK DIB¡1.Y000HH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast 2WOI ANJRIT, NGHEHWAE`NYA BWARBWAR BGT DIBHIOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast MALLLEEMMHMM IAINN`NI PPAAARTTYYY NGGGGEEIWEEEEEE DEEBBBBBIIOOOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast NNGGGEEWEHEEE BBBR`AUUTTA4ALL BANGGETT DDIIBBEEIIOOHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast ADHA YGAAN9 NG0EE`A33M33K DI BIlNG90H')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast UUDDAAHHFHH MUALLA`III NNGGEEWEEEE BBRUUTTA4ALL BANGGETT DDIIBBEEIYYYIOOHHHn')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(400)
    client.send_message(entity=channel_entity, message='.gcast pp NNGGEFSEWEEEE BB`RUUTTA4ALL BANGGETT DDIIBBEEIIOOHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast BBOECIL DI GGANGBNK D`IHIIIBHIOOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast UUDY`DDEHH BASSSAHHH` BANGETT KK ITU SINII BURUUANNNN')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast O`OUHH INI DIA YYAANG VHIRAL CUSSSS BHI0000')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast SZ`III ALEEAAA ANGEEEEE BB1HYYYYYTOOOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast SS,IARAAA`N LANGSUNG PEER0MEEKAAANN DIB;1Y000HHKKkk')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast CEE`EKKK DI PLHOPJIL AKU ADDA YANG LAGI ENHAK ENHAK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast OO`UHHMEX PINKKKK FULL DDESAG BANGET DI BYOCHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast AA4KUU`UUU COOLLLMEEEEKKK BHYYYEIOOOOOOKK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast JIIILLBBB`OOOBBS OMMMMEEECGK DEBHHHHHIOIOOOOH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast AADDD`DHA YYYAAN9 NG0EE3E3M3E3K DI BIlNG90H')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast UUU`D.DADAHHHH MULLAIII NNGEGEEEWEEEE BBRUUTTA4ALL BANGGETT DDIIBBEEIYYYIOOHHHn')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(400)
    client.send_message(entity=channel_entity, message='.gcast p`p NN`HGGEEDWEEEE BBRRRUUUTTA4AALL BANGGETT DDIIBBEEIIOOHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast BB0OO``CIL DI GGGGAANGBNK DI1HIIlIIBHIOOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast UUIDDD`DDEEEEEHH BASSAHHH BBANNGGETT KK ITU SINII BURUUANNNN')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast OOOHHH `IN.NI DDIA YANG DVAHIRAL CUSSSSSSS BHI0000')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast R2WWI`WOI A.NJRIT, NGHEWENYA BWARABWAR BGT DIBHIOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast MALLLE`EEMMR.MM IINNNI PPAAARTTYYY NGGAGGEEIWEEEEEE DEEBBBBBBIIOOOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(300)
    client.send_message(entity=channel_entity, message='.gcast NNNGG`GEEEWEEEE BBBRUUTTA4ALL BANNAGGGETT DDIIBBEEEIIOOHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast ADDH`A YAAN9G NG0EIE33M33K DI BIlANG90H')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast SSSIIAAI`ARAAAN LANGSUNG PER0MEEAEKAAANN DIB;1Y000HHHKKkk')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast LLISTINIIi`IERR KIAA OMEXKCG BAWBRBAWRR DBYOHGHHHFF')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast OOOUH`HMEX PINKKK FULL DESAAG BANNAGGEET DI BYOCHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast AQKU `ANGGHEKKKK PARAHHHHDI BYUIAOHHHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast CCH``OLLLMEE3KKKKKINN`NN BBBBHHHIIIYAYUUUUHHHUK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast `CCH`AHOLLLL MEEEKKKINNNN BHHHYIIIIOUYHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast NHN-GAUEWE`EE BBRUTALLL BGTTT DI BIYOOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast `CHOLLLLMEEFEKKKIA~NNNN BHIHHYIIIOUYHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast ``MMA`4MMIII~I OOEMAMEEEXXCKK BBBHYIIIOOUKKIII')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast OO.OHHHME.~EECXKKINANN MOMMMIIIIIKUI BHHHHIIIIOOOYOOOOK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast MMAA4AMMIIII ~OOEM1MEEEXXCKK BBBHYIIIOOUKKIIII')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast FFULL OSMECCCKSS ~DESAHHH DIYY BIYYOOOUHHHH1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast BATLEEE  OMEKKK VS ~BATLEEE COLY DI BIUHHHHHH1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast UD4AHHHHHH D1MULAIIIII ~BURU4NNNNNN CEKKKKKK B1000KKKKKKCKKK1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast TIEEEEMMEEEININN ~AKKKUUU SAINGGGEEEEKK DDDEEEBEEE1O')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast MEM31MMMMKS~ TEMBEM DIIBYIIOOU AK SAYANGGGF')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast LIVFEEE NGEUWEEE ~£UDAAHHH MULAIIII DI BIYOOOOU BURU JOINNNN1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast TIEEEMMMEEEININN £AKKKUUU SAINGDGGEEEEKK DDDEEEBEEEOI')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast SOK1NN TM0 C`UANN ¢DIBYIOUHHHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    client.send_message(entity=channel_entity, message='.gcast ANA4K SMA NGEU33 ¢SAMA OM` DI BBHHEYOKKK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : iruz')
    sleep(320)
    
  except:
    print(f'{hijau} Gcast gagal.! {putih} gcast by : iruz')
    sleep(120)

sys.exit()
client.disconnect()
